@url_dev = http://localhost:3056/v1/api/


// signup
POST {{url_dev}}shop/signup
Content-Type: application/json
x-api-key: asdasd

{
    "name": "222",
    "email": "222@gmail.com",
    "password": "222"
}
